### ISSUE TITLE
万一出现安装失败的情况

### ISSUE THREAD

**Issue by AIlll** [a-voyager/AutoInstaller#3]
怎么说

**Comment by a-voyager** [comment]
安装失败就自动跳回原有界面了，因为目前还没想到如何监听安装进度

**Comment by AIlll** [comment]
@a-voyager 我是采用root静默安装的    如果安装失败，不会出现什么变化是吧

**Comment by a-voyager** [comment]
是的，不会有任何变化。我在内部函数其实做了判断成功与否的，installUseRoot() 这个函数返回 boolean 表示是否安装成功，但在对外接口中是忽略了它的返回值的

**Comment by AIlll** [comment]
@a-voyager 那就不太好知道安装失败了

**Comment by maxcine13** [comment]
有适配华为和三星吗

**Comment by a-voyager** [comment]
@mxfeng 华为上可以，手里没有三星机器，暂未测试
