### ISSUE TITLE
7.0上无法使用啊。

### ISSUE THREAD

**Issue by UbuntuLover** [a-voyager/AutoInstaller#7]
老出现 解析包出现问题这个错误

**Comment by a-voyager** [comment]
删除下载目录的安装包试试呢

**Comment by UbuntuLover** [comment]
额，或许我昨天没描述好，先道歉 。
是这样的 Android7.0 userdebug版本的系统。
Git拉代码到Android Studio中建立工程，采用你的从本地安装文件，我把测试APK（其实是豌豆荚apk）改名为test.apk放在/storage/emulated/0/Download目录下，然后运行程序。使用ROOT方式安装无任何反应。使用AUTO方式安装提示解析包错误。

**Comment by a-voyager** [comment]
我目前只能猜测可能为以下原因，给你一些建议：
1、确保工程为最新的工程，最新的工程或v1.1版才是适配了 7.0 的，同时确保你的测试 APK 能够正常安装，或者换个 APK 试试
2、很有可能是路径问题，建议代码中打印出指定的路径是不是 /storage/emulated/0/Download，不同手机往往不同表现，有可能是 /storage/emulated/1/Download，也可能是 /storage/sdcard/Download
3、7.0 中引入了 v2 签名，该签名可能导致应用内更新存在问题，禁用掉试试，singConfigs 中加入 v2SigningEnabled false

**Comment by UbuntuLover** [comment]
首先感谢老哥的无私开源以及详细解答。
1.我已经git pull来同步最新的代码了。同时，测试所用的APK是在百度上下载的豌豆荚apk，手动点击是可以安装的，因此这一点可以保证.
2.代码中路径打印确实是/storage/emulated/0/Download.仔细阅读了一下你的res/xml目录下的那个关于fileprovider的代码，应该是只共享了/storage/emulated/0/Download这个文件夹出去。
3.尝试使用ROOT方式安装，回溯日志为
![image](https://user-images.githubusercontent.com/11254216/34372424-84e7cf44-eb0f-11e7-9d77-a5a201f3a9f0.png)
ROOT方式应该是向手机申请SU权限，然后执行pm install命令来安装APK文件的。现在就不太明白这个权限问题。
请问如何解决这个问题呢？？

**Comment by UbuntuLover** [comment]
另外，在signingConfigs节点下关闭了V2签名也是一样的。

**Comment by a-voyager** [comment]
v1.2 已修复
