### ISSUE TITLE
5.1.1平板上老是会弹出“辅助功能服务”

### ISSUE THREAD

**Issue by VincentJ1989** [a-voyager/AutoInstaller#8]
在安装的时候会t跳到“无障碍”页面，要求我们手动去打开app的”应用自动安装服务“。这个是什么原因引起的？有办法可以避免吗？

**Comment by UbuntuLover** [comment]
。。。老哥你去阅读源码吧。。。可以用ROOT方式安装啊。5.1的系统亲测完美使用。

**Comment by VincentJ1989** [comment]
大佬你是说不用BOTH改用ROOT吗？我记得我之前3个都测试了都会弹出来啊：（

**Comment by UbuntuLover** [comment]
...不是 用了ROOT可以完全静默安装。本质上是调用了adb shell命令 pm install 来安装。 -r参数表示覆盖安装。至于你说都会弹出来说明你的设备可能没有ROOT。或者是你修改了代码。多跟跟代码吧。。。我也遇上问题了。。。

**Comment by VincentJ1989** [comment]
是的，设备没有Root。你的意思是说得设备Root才可以完全静默安装吗？

**Comment by UbuntuLover** [comment]
是的。

**Comment by VincentJ1989** [comment]
好的，谢谢大佬，我自己再看看

**Comment by UbuntuLover** [comment]
我很菜的。。。。。
